"""Curated-indicator namespaces for KOSIS's 100대 지표, grouped by category.

Generated by tools/gen_curation.py from tools/curation_design.tsv -- do not edit
by hand. Each class mirrors one KOSIS category; leaves are :class:`Indicator`
objects pointing at a source table. Table and frequency were auto-extracted from
the KOSIS portal and may need per-indicator verification.
"""

from __future__ import annotations

from functools import cached_property

from ..types import Frequency
from ._indicator import Indicator, IndicatorSpec, _DataClient

__all__ = ["_CurationGroups"]


class _Population:
    """Curated indicators under ``population``."""

    def __init__(self, client: _DataClient) -> None:
        self.single_person_households = Indicator(
            client,
            IndicatorSpec(
                path="population.single_person_households",
                name_ko="1인가구",
                name_en="single_person_households",
                group="population",
                org_id="101",
                tbl_id="DT_1PL1502",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.elderly_population = Indicator(
            client,
            IndicatorSpec(
                path="population.elderly_population",
                name_ko="고령인구",
                name_en="elderly_population",
                group="population",
                org_id="101",
                tbl_id="DT_1BPA003",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.internal_migrants = Indicator(
            client,
            IndicatorSpec(
                path="population.internal_migrants",
                name_ko="국내인구 이동자수",
                name_en="internal_migrants",
                group="population",
                org_id="101",
                tbl_id="DT_1B26003_A01",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.aging_index = Indicator(
            client,
            IndicatorSpec(
                path="population.aging_index",
                name_ko="노령화지수",
                name_en="aging_index",
                group="population",
                org_id="101",
                tbl_id="DT_1BPA002",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.multicultural_households = Indicator(
            client,
            IndicatorSpec(
                path="population.multicultural_households",
                name_ko="다문화가구",
                name_en="multicultural_households",
                group="population",
                org_id="101",
                tbl_id="DT_1JD1501",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.registered_foreigners = Indicator(
            client,
            IndicatorSpec(
                path="population.registered_foreigners",
                name_ko="외국인등록인구",
                name_en="registered_foreigners",
                group="population",
                org_id="111",
                tbl_id="DT_1B040A10",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.projected_population = Indicator(
            client,
            IndicatorSpec(
                path="population.projected_population",
                name_ko="인구(장래인구추계)",
                name_en="projected_population",
                group="population",
                org_id="101",
                tbl_id="DT_1BPA002",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.population_density = Indicator(
            client,
            IndicatorSpec(
                path="population.population_density",
                name_ko="인구밀도",
                name_en="population_density",
                group="population",
                org_id="101",
                tbl_id="DT_1B08024",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.resident_registered_households = Indicator(
            client,
            IndicatorSpec(
                path="population.resident_registered_households",
                name_ko="주민등록세대수",
                name_en="resident_registered_households",
                group="population",
                org_id="101",
                tbl_id="DT_1B040B3",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.resident_registered_population = Indicator(
            client,
            IndicatorSpec(
                path="population.resident_registered_population",
                name_ko="주민등록인구",
                name_en="resident_registered_population",
                group="population",
                org_id="101",
                tbl_id="DT_1B040A3",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.births = Indicator(
            client,
            IndicatorSpec(
                path="population.births",
                name_ko="출생아수",
                name_en="births",
                group="population",
                org_id="101",
                tbl_id="DT_1B8000F",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.total_fertility_rate = Indicator(
            client,
            IndicatorSpec(
                path="population.total_fertility_rate",
                name_ko="합계출산율",
                name_en="total_fertility_rate",
                group="population",
                org_id="101",
                tbl_id="DT_1B8000H",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.marriages = Indicator(
            client,
            IndicatorSpec(
                path="population.marriages",
                name_ko="혼인건수",
                name_en="marriages",
                group="population",
                org_id="101",
                tbl_id="DT_1B8000F",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.households = Indicator(
            client,
            IndicatorSpec(
                path="population.households",
                name_ko="가구수",
                name_en="households",
                group="population",
                org_id="101",
                tbl_id="DT_1IN1502",
                frequency=Frequency.ANNUAL,
                obj_levels=("00",),
            ),
        )
        self.average_household_size = Indicator(
            client,
            IndicatorSpec(
                path="population.average_household_size",
                name_ko="평균 가구원수",
                name_en="average_household_size",
                group="population",
                org_id="101",
                tbl_id="DT_1JC1516",
                frequency=Frequency.ANNUAL,
                obj_levels=("00", "00"),
            ),
        )


class _Economy:
    """Curated indicators under ``economy``."""

    def __init__(self, client: _DataClient) -> None:
        self.composite_economic_index = Indicator(
            client,
            IndicatorSpec(
                path="economy.composite_economic_index",
                name_ko="경기종합지수",
                name_en="composite_economic_index",
                group="economy",
                org_id="101",
                tbl_id="DT_1C8015",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.gdp_growth_rate = Indicator(
            client,
            IndicatorSpec(
                path="economy.gdp_growth_rate",
                name_ko="경제성장률",
                name_en="gdp_growth_rate",
                group="economy",
                org_id="301",
                tbl_id="DT_200Y102",
                frequency=Frequency.QUARTERLY,
            ),
        )
        self.gdp = Indicator(
            client,
            IndicatorSpec(
                path="economy.gdp",
                name_ko="국내총생산(GDP)",
                name_en="gdp",
                group="economy",
                org_id="301",
                tbl_id="DT_200Y105",
                frequency=Frequency.QUARTERLY,
            ),
        )
        self.equipment_investment_index = Indicator(
            client,
            IndicatorSpec(
                path="economy.equipment_investment_index",
                name_ko="설비투자지수",
                name_en="equipment_investment_index",
                group="economy",
                org_id="101",
                tbl_id="DT_1F70011",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.consumer_sentiment_index = Indicator(
            client,
            IndicatorSpec(
                path="economy.consumer_sentiment_index",
                name_ko="소비자심리지수",
                name_en="consumer_sentiment_index",
                group="economy",
                org_id="301",
                tbl_id="DT_511Y002",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.exports = Indicator(
            client,
            IndicatorSpec(
                path="economy.exports",
                name_ko="수출액",
                name_en="exports",
                group="economy",
                org_id="360",
                tbl_id="DT_1R11001_FRM101",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.bank_lending_rate = Indicator(
            client,
            IndicatorSpec(
                path="economy.bank_lending_rate",
                name_ko="예금은행 대출금리",
                name_en="bank_lending_rate",
                group="economy",
                org_id="301",
                tbl_id="DT_121Y006",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.all_industry_production_index = Indicator(
            client,
            IndicatorSpec(
                path="economy.all_industry_production_index",
                name_ko="전산업생산지수",
                name_en="all_industry_production_index",
                group="economy",
                org_id="101",
                tbl_id="DT_1JH20201",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.sme_count = Indicator(
            client,
            IndicatorSpec(
                path="economy.sme_count",
                name_ko="중소기업수",
                name_en="sme_count",
                group="economy",
                org_id="142",
                tbl_id="DT_BR_A001",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.grdp = Indicator(
            client,
            IndicatorSpec(
                path="economy.grdp",
                name_ko="지역내총생산(GRDP)",
                name_en="grdp",
                group="economy",
                org_id="101",
                tbl_id="DT_1C91",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.startups = Indicator(
            client,
            IndicatorSpec(
                path="economy.startups",
                name_ko="창업기업수",
                name_en="startups",
                group="economy",
                org_id="142",
                tbl_id="DT_142N_G201",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.kospi = Indicator(
            client,
            IndicatorSpec(
                path="economy.kospi",
                name_ko="코스피지수(KOSPI)",
                name_en="kospi",
                group="economy",
                org_id="343",
                tbl_id="DT_343_2010_S0027",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.consolidated_fiscal_balance = Indicator(
            client,
            IndicatorSpec(
                path="economy.consolidated_fiscal_balance",
                name_ko="통합재정수지",
                name_en="consolidated_fiscal_balance",
                group="economy",
                org_id="184",
                tbl_id="DT_102N_AD01",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.business_establishments = Indicator(
            client,
            IndicatorSpec(
                path="economy.business_establishments",
                name_ko="사업체수",
                name_en="business_establishments",
                group="economy",
                org_id="101",
                tbl_id="DT_1K52D01",
                frequency=Frequency.ANNUAL,
                obj_levels=("00", "ALL", "0"),
            ),
        )


class _EnvironmentEnergy:
    """Curated indicators under ``environment_energy``."""

    def __init__(self, client: _DataClient) -> None:
        self.electricity_consumption_per_capita = Indicator(
            client,
            IndicatorSpec(
                path="environment_energy.electricity_consumption_per_capita",
                name_ko="1인당 전력소비량",
                name_en="electricity_consumption_per_capita",
                group="environment_energy",
                org_id="388",
                tbl_id="TX_38803_A026",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.pm10_concentration = Indicator(
            client,
            IndicatorSpec(
                path="environment_energy.pm10_concentration",
                name_ko="미세먼지 농도(PM 10)",
                name_en="pm10_concentration",
                group="environment_energy",
                org_id="106",
                tbl_id="DT_106N_03_0200045",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.power_generation = Indicator(
            client,
            IndicatorSpec(
                path="environment_energy.power_generation",
                name_ko="발전실적",
                name_en="power_generation",
                group="environment_energy",
                org_id="388",
                tbl_id="TX_38803_A014",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.household_waste_generation = Indicator(
            client,
            IndicatorSpec(
                path="environment_energy.household_waste_generation",
                name_ko="생활폐기물 발생량",
                name_en="household_waste_generation",
                group="environment_energy",
                org_id="106",
                tbl_id="DT_106N_29_2020005",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.renewable_energy_production = Indicator(
            client,
            IndicatorSpec(
                path="environment_energy.renewable_energy_production",
                name_ko="신·재생에너지생산량",
                name_en="renewable_energy_production",
                group="environment_energy",
                org_id="337",
                tbl_id="DT_337N_A001",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.greenhouse_gas_emissions = Indicator(
            client,
            IndicatorSpec(
                path="environment_energy.greenhouse_gas_emissions",
                name_ko="온실가스배출량",
                name_en="greenhouse_gas_emissions",
                group="environment_energy",
                org_id="106",
                tbl_id="DT_106N_99_2800020",
                frequency=Frequency.ANNUAL,
            ),
        )


class _HealthWelfare:
    """Curated indicators under ``health_welfare``."""

    def __init__(self, client: _DataClient) -> None:
        self.infectious_disease_cases = Indicator(
            client,
            IndicatorSpec(
                path="health_welfare.infectious_disease_cases",
                name_ko="감염병발생건수",
                name_en="infectious_disease_cases",
                group="health_welfare",
                org_id="177",
                tbl_id="DT_117052_A001",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.basic_livelihood_recipients = Indicator(
            client,
            IndicatorSpec(
                path="health_welfare.basic_livelihood_recipients",
                name_ko="국민기초생활보장수급자수",
                name_en="basic_livelihood_recipients",
                group="health_welfare",
                org_id="117",
                tbl_id="DT_11714_N001",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.life_expectancy = Indicator(
            client,
            IndicatorSpec(
                path="health_welfare.life_expectancy",
                name_ko="기대수명",
                name_en="life_expectancy",
                group="health_welfare",
                org_id="101",
                tbl_id="DT_1B41",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.obesity_rate = Indicator(
            client,
            IndicatorSpec(
                path="health_welfare.obesity_rate",
                name_ko="비만율",
                name_en="obesity_rate",
                group="health_welfare",
                org_id="177",
                tbl_id="DT_11702_N101",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.cancer_cases = Indicator(
            client,
            IndicatorSpec(
                path="health_welfare.cancer_cases",
                name_ko="암발생자수",
                name_en="cancer_cases",
                group="health_welfare",
                org_id="117",
                tbl_id="DT_117N_A00023",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.daycare_centers = Indicator(
            client,
            IndicatorSpec(
                path="health_welfare.daycare_centers",
                name_ko="어린이집수",
                name_en="daycare_centers",
                group="health_welfare",
                org_id="112",
                tbl_id="DT_15407_NN001",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.drinking_rate = Indicator(
            client,
            IndicatorSpec(
                path="health_welfare.drinking_rate",
                name_ko="음주율",
                name_en="drinking_rate",
                group="health_welfare",
                org_id="177",
                tbl_id="DT_11702_N012",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.medical_institutions = Indicator(
            client,
            IndicatorSpec(
                path="health_welfare.medical_institutions",
                name_ko="의료기관수",
                name_en="medical_institutions",
                group="health_welfare",
                org_id="354",
                tbl_id="DT_MIRE01",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.medical_personnel = Indicator(
            client,
            IndicatorSpec(
                path="health_welfare.medical_personnel",
                name_ko="의료인력수",
                name_en="medical_personnel",
                group="health_welfare",
                org_id="354",
                tbl_id="DT_HIRA4T",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.suicide_rate = Indicator(
            client,
            IndicatorSpec(
                path="health_welfare.suicide_rate",
                name_ko="자살률",
                name_en="suicide_rate",
                group="health_welfare",
                org_id="101",
                tbl_id="DT_1B34E01",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.persons_with_disabilities = Indicator(
            client,
            IndicatorSpec(
                path="health_welfare.persons_with_disabilities",
                name_ko="장애인인구",
                name_en="persons_with_disabilities",
                group="health_welfare",
                org_id="117",
                tbl_id="DT_11761_N005",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.average_height = Indicator(
            client,
            IndicatorSpec(
                path="health_welfare.average_height",
                name_ko="평균신장",
                name_en="average_height",
                group="health_welfare",
                org_id="350",
                tbl_id="DT_35007_N130",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.death_rate = Indicator(
            client,
            IndicatorSpec(
                path="health_welfare.death_rate",
                name_ko="사망률",
                name_en="death_rate",
                group="health_welfare",
                org_id="101",
                tbl_id="DT_1B34E13",
                frequency=Frequency.ANNUAL,
                obj_levels=("0", "00", "0"),
            ),
        )


class _EducationLabor:
    """Curated indicators under ``education_labor``."""

    def __init__(self, client: _DataClient) -> None:
        self.career_interrupted_women = Indicator(
            client,
            IndicatorSpec(
                path="education_labor.career_interrupted_women",
                name_ko="경력단절여성",
                name_en="career_interrupted_women",
                group="education_labor",
                org_id="101",
                tbl_id="DT_1ES4H06S",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.economically_active_population = Indicator(
            client,
            IndicatorSpec(
                path="education_labor.economically_active_population",
                name_ko="경제활동인구",
                name_en="economically_active_population",
                group="education_labor",
                org_id="101",
                tbl_id="DT_1DA7001S",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.employment_rate = Indicator(
            client,
            IndicatorSpec(
                path="education_labor.employment_rate",
                name_ko="고용률",
                name_en="employment_rate",
                group="education_labor",
                org_id="101",
                tbl_id="DT_1DA7001S",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.working_hours = Indicator(
            client,
            IndicatorSpec(
                path="education_labor.working_hours",
                name_ko="근로시간",
                name_en="working_hours",
                group="education_labor",
                org_id="118",
                tbl_id="DT_118N_MON054",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.wages = Indicator(
            client,
            IndicatorSpec(
                path="education_labor.wages",
                name_ko="근로임금",
                name_en="wages",
                group="education_labor",
                org_id="118",
                tbl_id="DT_118N_MON054",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.labor_productivity_index = Indicator(
            client,
            IndicatorSpec(
                path="education_labor.labor_productivity_index",
                name_ko="노동생산성지수",
                name_en="labor_productivity_index",
                group="education_labor",
                org_id="344",
                tbl_id="DT_344N_1D8A_AA",
                frequency=Frequency.QUARTERLY,
            ),
        )
        self.universities = Indicator(
            client,
            IndicatorSpec(
                path="education_labor.universities",
                name_ko="대학교 수",
                name_en="universities",
                group="education_labor",
                org_id="334",
                tbl_id="DT_1963003_013",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.dual_income_households = Indicator(
            client,
            IndicatorSpec(
                path="education_labor.dual_income_households",
                name_ko="맞벌이가구",
                name_en="dual_income_households",
                group="education_labor",
                org_id="101",
                tbl_id="DT_1ES4F09S",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.job_vacancies = Indicator(
            client,
            IndicatorSpec(
                path="education_labor.job_vacancies",
                name_ko="빈일자리",
                name_en="job_vacancies",
                group="education_labor",
                org_id="118",
                tbl_id="DT_118N_MON066",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.unemployment_rate = Indicator(
            client,
            IndicatorSpec(
                path="education_labor.unemployment_rate",
                name_ko="실업률",
                name_en="unemployment_rate",
                group="education_labor",
                org_id="101",
                tbl_id="DT_1DA7001S",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.school_students = Indicator(
            client,
            IndicatorSpec(
                path="education_labor.school_students",
                name_ko="초중고학생수",
                name_en="school_students",
                group="education_labor",
                org_id="334",
                tbl_id="DT_1963003_004",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.private_education_expenditure = Indicator(
            client,
            IndicatorSpec(
                path="education_labor.private_education_expenditure",
                name_ko="학생사교육비",
                name_en="private_education_expenditure",
                group="education_labor",
                org_id="101",
                tbl_id="DT_1PE003",
                frequency=Frequency.ANNUAL,
            ),
        )


class _IncomeConsumption:
    """Curated indicators under ``income_consumption``."""

    def __init__(self, client: _DataClient) -> None:
        self.household_debt = Indicator(
            client,
            IndicatorSpec(
                path="income_consumption.household_debt",
                name_ko="가구부채",
                name_en="household_debt",
                group="income_consumption",
                org_id="101",
                tbl_id="DT_1HDAAA01",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.household_consumption_expenditure = Indicator(
            client,
            IndicatorSpec(
                path="income_consumption.household_consumption_expenditure",
                name_ko="가구소비지출",
                name_en="household_consumption_expenditure",
                group="income_consumption",
                org_id="101",
                tbl_id="DT_1L9U101",
                frequency=Frequency.QUARTERLY,
            ),
        )
        self.median_household_income = Indicator(
            client,
            IndicatorSpec(
                path="income_consumption.median_household_income",
                name_ko="가구중위소득",
                name_en="median_household_income",
                group="income_consumption",
                org_id="101",
                tbl_id="DT_1HDALF05",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.farm_household_income = Indicator(
            client,
            IndicatorSpec(
                path="income_consumption.farm_household_income",
                name_ko="농가소득",
                name_en="farm_household_income",
                group="income_consumption",
                org_id="101",
                tbl_id="DT_1EA1501",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.ppi = Indicator(
            client,
            IndicatorSpec(
                path="income_consumption.ppi",
                name_ko="생산자물가지수",
                name_en="ppi",
                group="income_consumption",
                org_id="301",
                tbl_id="DT_404Y014",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.cpi = Indicator(
            client,
            IndicatorSpec(
                path="income_consumption.cpi",
                name_ko="소비자물가지수",
                name_en="cpi",
                group="income_consumption",
                org_id="101",
                tbl_id="DT_1J22001",
                frequency=Frequency.MONTHLY,
            ),
        )


class _Leisure:
    """Curated indicators under ``leisure``."""

    def __init__(self, client: _DataClient) -> None:
        self.books_read_per_capita = Indicator(
            client,
            IndicatorSpec(
                path="leisure.books_read_per_capita",
                name_ko="1인당 평균독서권수",
                name_en="books_read_per_capita",
                group="leisure",
                org_id="101",
                tbl_id="DT_1SSCL020R",
                frequency=Frequency.MULTIYEAR,
            ),
        )
        self.domestic_travel_rate = Indicator(
            client,
            IndicatorSpec(
                path="leisure.domestic_travel_rate",
                name_ko="국내여행 경험률",
                name_en="domestic_travel_rate",
                group="leisure",
                org_id="101",
                tbl_id="DT_1SSCL050R",
                frequency=Frequency.MULTIYEAR,
            ),
        )
        self.libraries = Indicator(
            client,
            IndicatorSpec(
                path="leisure.libraries",
                name_ko="도서관수",
                name_en="libraries",
                group="leisure",
                org_id="113",
                tbl_id="DT_113_STBL_1028308",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.arts_attendance_rate = Indicator(
            client,
            IndicatorSpec(
                path="leisure.arts_attendance_rate",
                name_ko="문화예술행사 관람률",
                name_en="arts_attendance_rate",
                group="leisure",
                org_id="113",
                tbl_id="DT_113_STBL_1013509",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.smartphone_overdependence_rate = Indicator(
            client,
            IndicatorSpec(
                path="leisure.smartphone_overdependence_rate",
                name_ko="스마트폰 과의존 위험군",
                name_en="smartphone_overdependence_rate",
                group="leisure",
                org_id="127",
                tbl_id="DT_120019N_2016_001",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.inbound_tourists = Indicator(
            client,
            IndicatorSpec(
                path="leisure.inbound_tourists",
                name_ko="외래관광객수",
                name_en="inbound_tourists",
                group="leisure",
                org_id="314",
                tbl_id="DT_TRD_TGT_ENT_AGG_MONTH",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.overseas_travel_rate = Indicator(
            client,
            IndicatorSpec(
                path="leisure.overseas_travel_rate",
                name_ko="해외여행 경험률",
                name_en="overseas_travel_rate",
                group="leisure",
                org_id="101",
                tbl_id="DT_1SSCL060R",
                frequency=Frequency.MULTIYEAR,
            ),
        )


class _HousingTransport:
    """Curated indicators under ``housing_transport``."""

    def __init__(self, client: _DataClient) -> None:
        self.urban_population_ratio = Indicator(
            client,
            IndicatorSpec(
                path="housing_transport.urban_population_ratio",
                name_ko="도시지역 인구비율",
                name_en="urban_population_ratio",
                group="housing_transport",
                org_id="460",
                tbl_id="TX_315_2009_H1001",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.housing_construction_permits = Indicator(
            client,
            IndicatorSpec(
                path="housing_transport.housing_construction_permits",
                name_ko="주택건설 인허가수",
                name_en="housing_construction_permits",
                group="housing_transport",
                org_id="116",
                tbl_id="DT_MLTM_1952",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.housing_sales_price_index = Indicator(
            client,
            IndicatorSpec(
                path="housing_transport.housing_sales_price_index",
                name_ko="주택매매가격지수",
                name_en="housing_sales_price_index",
                group="housing_transport",
                org_id="408",
                tbl_id="DT_30404_A012",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.housing_supply_ratio = Indicator(
            client,
            IndicatorSpec(
                path="housing_transport.housing_supply_ratio",
                name_ko="주택보급률",
                name_en="housing_supply_ratio",
                group="housing_transport",
                org_id="116",
                tbl_id="DT_MLTM_2100",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.housing_units = Indicator(
            client,
            IndicatorSpec(
                path="housing_transport.housing_units",
                name_ko="주택수",
                name_en="housing_units",
                group="housing_transport",
                org_id="101",
                tbl_id="DT_1JU1501",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.land_price_change_rate = Indicator(
            client,
            IndicatorSpec(
                path="housing_transport.land_price_change_rate",
                name_ko="지가변동률",
                name_en="land_price_change_rate",
                group="housing_transport",
                org_id="408",
                tbl_id="DT_PLCAHTUSE",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.registered_motorcycles = Indicator(
            client,
            IndicatorSpec(
                path="housing_transport.registered_motorcycles",
                name_ko="이륜차 신고대수",
                name_en="registered_motorcycles",
                group="housing_transport",
                org_id="116",
                tbl_id="DT_MLTM_5559",
                frequency=Frequency.MONTHLY,
                obj_levels=("ALL", "13102866057B.0001", "13102866057C.0001"),
            ),
        )
        self.registered_vehicles = Indicator(
            client,
            IndicatorSpec(
                path="housing_transport.registered_vehicles",
                name_ko="자동차 등록대수",
                name_en="registered_vehicles",
                group="housing_transport",
                org_id="116",
                tbl_id="DT_MLTM_5498",
                frequency=Frequency.MONTHLY,
                obj_levels=("ALL", "13102873443B.0001", "13102873443C.0005"),
            ),
        )
        self.land_area = Indicator(
            client,
            IndicatorSpec(
                path="housing_transport.land_area",
                name_ko="국토면적",
                name_en="land_area",
                group="housing_transport",
                org_id="101",
                tbl_id="DT_2KAA101",
                frequency=Frequency.ANNUAL,
            ),
        )


class _CrimeSafety:
    """Curated indicators under ``crime_safety``."""

    def __init__(self, client: _DataClient) -> None:
        self.traffic_accident_deaths = Indicator(
            client,
            IndicatorSpec(
                path="crime_safety.traffic_accident_deaths",
                name_ko="교통사고 사망자수",
                name_en="traffic_accident_deaths",
                group="crime_safety",
                org_id="132",
                tbl_id="DT_V_MOTA_011",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.crime_cases = Indicator(
            client,
            IndicatorSpec(
                path="crime_safety.crime_cases",
                name_ko="범죄발생건수",
                name_en="crime_cases",
                group="crime_safety",
                org_id="132",
                tbl_id="DT_132004_A001",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.industrial_accident_victims = Indicator(
            client,
            IndicatorSpec(
                path="crime_safety.industrial_accident_victims",
                name_ko="산업재해자수",
                name_en="industrial_accident_victims",
                group="crime_safety",
                org_id="118",
                tbl_id="DT_11806_N000",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.child_abuse_cases = Indicator(
            client,
            IndicatorSpec(
                path="crime_safety.child_abuse_cases",
                name_ko="아동학대건수",
                name_en="child_abuse_cases",
                group="crime_safety",
                org_id="117",
                tbl_id="DT_117064_A009",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.earthquake_frequency = Indicator(
            client,
            IndicatorSpec(
                path="crime_safety.earthquake_frequency",
                name_ko="지진발생빈도",
                name_en="earthquake_frequency",
                group="crime_safety",
                org_id="141",
                tbl_id="TX_14101_A001",
                frequency=Frequency.ANNUAL,
            ),
        )


class _Industry:
    """Curated indicators under ``industry``."""

    def __init__(self, client: _DataClient) -> None:
        self.rice_consumption_per_capita = Indicator(
            client,
            IndicatorSpec(
                path="industry.rice_consumption_per_capita",
                name_ko="1인당쌀소비량",
                name_en="rice_consumption_per_capita",
                group="industry",
                org_id="101",
                tbl_id="DT_1ED0001",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.cultivated_area = Indicator(
            client,
            IndicatorSpec(
                path="industry.cultivated_area",
                name_ko="경지면적",
                name_en="cultivated_area",
                group="industry",
                org_id="101",
                tbl_id="DT_1EB001",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.return_to_farming_population = Indicator(
            client,
            IndicatorSpec(
                path="industry.return_to_farming_population",
                name_ko="귀농인구",
                name_en="return_to_farming_population",
                group="industry",
                org_id="101",
                tbl_id="DT_1A02003",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.farm_population = Indicator(
            client,
            IndicatorSpec(
                path="industry.farm_population",
                name_ko="농가인구",
                name_en="farm_population",
                group="industry",
                org_id="101",
                tbl_id="DT_1EA1011",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.service_production_index = Indicator(
            client,
            IndicatorSpec(
                path="industry.service_production_index",
                name_ko="서비스업생산지수",
                name_en="service_production_index",
                group="industry",
                org_id="101",
                tbl_id="DT_1KC2020",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.retail_sales = Indicator(
            client,
            IndicatorSpec(
                path="industry.retail_sales",
                name_ko="소매판매액",
                name_en="retail_sales",
                group="industry",
                org_id="101",
                tbl_id="DT_1K41002",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.food_crop_production = Indicator(
            client,
            IndicatorSpec(
                path="industry.food_crop_production",
                name_ko="식량작물 생산량",
                name_en="food_crop_production",
                group="industry",
                org_id="101",
                tbl_id="DT_1ET0021",
                frequency=Frequency.ANNUAL,
            ),
        )
        self.online_shopping_transaction_value = Indicator(
            client,
            IndicatorSpec(
                path="industry.online_shopping_transaction_value",
                name_ko="온라인쇼핑몰 거래액",
                name_en="online_shopping_transaction_value",
                group="industry",
                org_id="101",
                tbl_id="DT_1KE10041",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.manufacturing_capacity_utilization_index = Indicator(
            client,
            IndicatorSpec(
                path="industry.manufacturing_capacity_utilization_index",
                name_ko="제조업 생산능력 및 가동률지수",
                name_en="manufacturing_capacity_utilization_index",
                group="industry",
                org_id="101",
                tbl_id="DT_1F32001",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.manufacturing_production_index = Indicator(
            client,
            IndicatorSpec(
                path="industry.manufacturing_production_index",
                name_ko="제조업생산지수",
                name_en="manufacturing_production_index",
                group="industry",
                org_id="101",
                tbl_id="DT_1F02001",
                frequency=Frequency.MONTHLY,
            ),
        )
        self.service_establishments = Indicator(
            client,
            IndicatorSpec(
                path="industry.service_establishments",
                name_ko="서비스업 사업체수",
                name_en="service_establishments",
                group="industry",
                org_id="101",
                tbl_id="DT_2KB9001",
                frequency=Frequency.ANNUAL,
                obj_levels=("00", "0"),
            ),
        )
        self.fishery_production = Indicator(
            client,
            IndicatorSpec(
                path="industry.fishery_production",
                name_ko="어업생산량",
                name_en="fishery_production",
                group="industry",
                org_id="101",
                tbl_id="DT_1EW0004",
                frequency=Frequency.ANNUAL,
                obj_levels=("0", "0", "00", "0"),
            ),
        )
        self.manufacturing_establishments = Indicator(
            client,
            IndicatorSpec(
                path="industry.manufacturing_establishments",
                name_ko="제조업 사업체수",
                name_en="manufacturing_establishments",
                group="industry",
                org_id="101",
                tbl_id="DT_1FS1001_S",
                frequency=Frequency.ANNUAL,
                obj_levels=("00", "ALL"),
            ),
        )


class _CurationGroups:
    """Mixin exposing the curated-indicator tree on a client.

    :class:`~pykosis.KOSIS` inherits this; each group builds lazily off the
    client's own ``fetch_data`` (set as ``_data_client``).
    """

    _data_client: _DataClient

    @cached_property
    def population(self) -> _Population:
        return _Population(self._data_client)

    @cached_property
    def economy(self) -> _Economy:
        return _Economy(self._data_client)

    @cached_property
    def environment_energy(self) -> _EnvironmentEnergy:
        return _EnvironmentEnergy(self._data_client)

    @cached_property
    def health_welfare(self) -> _HealthWelfare:
        return _HealthWelfare(self._data_client)

    @cached_property
    def education_labor(self) -> _EducationLabor:
        return _EducationLabor(self._data_client)

    @cached_property
    def income_consumption(self) -> _IncomeConsumption:
        return _IncomeConsumption(self._data_client)

    @cached_property
    def leisure(self) -> _Leisure:
        return _Leisure(self._data_client)

    @cached_property
    def housing_transport(self) -> _HousingTransport:
        return _HousingTransport(self._data_client)

    @cached_property
    def crime_safety(self) -> _CrimeSafety:
        return _CrimeSafety(self._data_client)

    @cached_property
    def industry(self) -> _Industry:
        return _Industry(self._data_client)

