"""Generate src/pykosis/curation/_generated.py from tools/curation_design.tsv.

The design worksheet holds one row per curated indicator (KOSIS's 100대 지표): its dotted
path, Korean/English names, source table, and frequency. This emits one class per group
(``_Population`` ...) building :class:`Indicator` objects, plus the ``_CurationGroups``
base that :class:`~pykosis.KOSIS` inherits.

Run:  uv run python tools/gen_curation.py
"""

from __future__ import annotations

import csv
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent
_DESIGN = _ROOT / "tools" / "curation_design.tsv"
_OUT = _ROOT / "src" / "pykosis" / "curation" / "_generated.py"

# Group order = KOSIS's own category order for the 100대 지표.
_GROUP_ORDER = [
    "population", "economy", "environment_energy", "health_welfare",
    "education_labor", "income_consumption", "leisure", "housing_transport",
    "crime_safety", "industry",
]
_FREQ_MEMBER = {
    "annual": "ANNUAL", "half_yearly": "HALF_YEARLY", "quarterly": "QUARTERLY",
    "monthly": "MONTHLY", "daily": "DAILY", "multiyear": "MULTIYEAR",
    "irregular": "IRREGULAR",
}


def _class_name(group: str) -> str:
    return "_" + "".join(word.capitalize() for word in group.split("_"))


def main() -> int:
    rows = list(csv.DictReader(_DESIGN.open(encoding="utf-8"), delimiter="\t"))
    by_group: dict[str, list[dict[str, str]]] = {g: [] for g in _GROUP_ORDER}
    for row in rows:
        by_group[row["group"]].append(row)

    lines: list[str] = [
        '"""Curated-indicator namespaces for KOSIS\'s 100대 지표, grouped by category.',
        "",
        "Generated by tools/gen_curation.py from tools/curation_design.tsv -- do not edit",
        "by hand. Each class mirrors one KOSIS category; leaves are :class:`Indicator`",
        "objects pointing at a source table. Table and frequency were auto-extracted from",
        "the KOSIS portal and may need per-indicator verification.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from functools import cached_property",
        "",
        "from ..types import Frequency",
        "from ._indicator import Indicator, IndicatorSpec, _DataClient",
        "",
        '__all__ = ["_CurationGroups"]',
        "",
    ]

    for group in _GROUP_ORDER:
        cls = _class_name(group)
        lines += [
            "",
            f"class {cls}:",
            f'    """Curated indicators under ``{group}``."""',
            "",
            "    def __init__(self, client: _DataClient) -> None:",
        ]
        for row in by_group[group]:
            freq = _FREQ_MEMBER[row["frequency"]]
            spec_lines = [
                f'                path="{row["path"]}",',
                f'                name_ko="{row["name_ko"]}",',
                f'                name_en="{row["name_en"]}",',
                f'                group="{group}",',
                f'                org_id="{row["org_id"]}",',
                f'                tbl_id="{row["tbl_id"]}",',
                f"                frequency=Frequency.{freq},",
            ]
            obj_levels = row.get("obj_levels", "").strip()
            if obj_levels:
                codes = ", ".join(f'"{c}"' for c in obj_levels.split("|"))
                comma = "," if "," not in codes else ""  # 1-tuple needs trailing comma
                spec_lines.append(f"                obj_levels=({codes}{comma}),")
            lines += [
                f"        self.{row['name_en']} = Indicator(",
                "            client,",
                "            IndicatorSpec(",
                *spec_lines,
                "            ),",
                "        )",
            ]
        lines.append("")

    lines += [
        "",
        "class _CurationGroups:",
        '    """Mixin exposing the curated-indicator tree on a client.',
        "",
        "    :class:`~pykosis.KOSIS` inherits this; each group builds lazily off the",
        "    client's own ``fetch_data`` (set as ``_data_client``).",
        '    """',
        "",
        "    _data_client: _DataClient",
        "",
    ]
    for group in _GROUP_ORDER:
        cls = _class_name(group)
        lines += [
            "    @cached_property",
            f"    def {group}(self) -> {cls}:",
            f"        return {cls}(self._data_client)",
            "",
        ]

    _OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    total = sum(len(v) for v in by_group.values())
    print(f"wrote {total} indicators in {len(_GROUP_ORDER)} groups -> {_OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
